name: Create release tag and release note.

on:
  push:
    branches: [ main ]

jobs:
  create-release-tag:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TZ: "Asia/Tokyo"

    steps:
       - uses: actions/checkout@v2
       # タグを作成する
       - name: create tag
         id: create_tag
         run: |
           TAG_NAME="v1-$(TZ=Asia/Tokyo date +%Y%m%d-%H%M%S)"
           echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
       - name: Create Release
         id: create_release
         uses: actions/create-release@v1
         env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
         with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Release
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false    
