name: Create release tag and release note.

on:
  push:
    branches: [ main ]

jobs:
  create-release-tag:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TZ: "Asia/Tokyo"

    steps:
       - uses: actions/checkout@v2
       # タグを作成する
       - name: create tag
         id: create_tag
         run: |
           TAG_NAME="v1-$(TZ=Asia/Tokyo date +%Y%m%d-%H%M%S)"
           echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
       # リリースノート作成
       - name: Create release note
         id: release
         uses: actions/create-release@v1
         env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
          tag_name: ${{ github.event.pull_request.title }}
          release_name: ${{ github.event.pull_request.title }}
          body: ${{ github.event.pull_request.body }}
          draft: false
          prerelease: false
