name: Create release tag and release note.

on:
  pull_request:
    branches:
      - main
    types: [ closed ]
jobs:
  create-release-tag:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: github.event.pull_request.merged == true
    steps:
       - uses: actions/checkout@v2
       # 前回のりリースタグを取得する
       - name: Get previous tag
         id: pre_tag
         run: |
          echo "PRE_TAG=$(curl -H 'Accept: application/vnd.github.v3+json' -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .tag_name)" >> $GITHUB_ENV
       # タグを作成する
       - name: create tag
         id: create_tag
         run: |
           TAG_NAME="${{ github.event.pull_request.title }}"
           echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
       # リリースノート作成
       - name: Create release note
         id: release
         uses: actions/create-release@v1
         env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: ${{ env.TAG_NAME }}
          body: ${{ env.PRE_TAG }}
          draft: false
          prerelease: false
       
