name: Create release tag and release note.

on:
  push:
    branches: [ main ]
jobs:
  create-release-tag:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
     - uses: actions/checkout@v2
     - run: git fetch origin ${{ github.event.pull_request.head.ref }}
     - run: git checkout ${{ github.event.pull_request.head.ref }}
     - run: git tag `echo '${{ github.event.pull_request.head.ref }}' | sed 's/release\///'`
     - run: git push origin `echo '${{ github.event.pull_request.head.ref }}' | sed 's/release\///'`
      
